// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFOIzMkKStbRpsM2dtNoLJcTbWp83xe9w',
    appId: '1:475890223603:web:df216926b600644c2f6a86',
    messagingSenderId: '475890223603',
    projectId: 'geoquiz-7790d',
    authDomain: 'geoquiz-7790d.firebaseapp.com',
    databaseURL: 'https://geoquiz-7790d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'geoquiz-7790d.firebasestorage.app',
    measurementId: 'G-93XEQYKCFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD6CQT1bx__NH8figYqT57RMwZW-xKTzA',
    appId: '1:475890223603:android:738e8f34a1fa4fc32f6a86',
    messagingSenderId: '475890223603',
    projectId: 'geoquiz-7790d',
    databaseURL: 'https://geoquiz-7790d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'geoquiz-7790d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7g2ZJ519gaAtE_t3rhNkPANUTtM3T0U0',
    appId: '1:475890223603:ios:df442053dec5eb692f6a86',
    messagingSenderId: '475890223603',
    projectId: 'geoquiz-7790d',
    databaseURL: 'https://geoquiz-7790d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'geoquiz-7790d.firebasestorage.app',
    iosClientId: '475890223603-3nvhvvb16b5f6dee1qufv4vnvb8sv79c.apps.googleusercontent.com',
    iosBundleId: 'com.example.futko',
  );

}