// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAprAmk1hPhlNbkQhgTSjIeEfmFIlfK18M',
    appId: '1:671381491956:web:5a85e868be8a6db82dcea1',
    messagingSenderId: '671381491956',
    projectId: 'futko-battle',
    authDomain: 'futko-battle.firebaseapp.com',
    storageBucket: 'futko-battle.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_BgMDvlebp2-H-BULVTVGBdrorl6GyGE',
    appId: '1:671381491956:android:280caebbd97b8d102dcea1',
    messagingSenderId: '671381491956',
    projectId: 'futko-battle',
    storageBucket: 'futko-battle.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3RwnQpSYI3WnnnoDTqe9m62gjJtYWzUs',
    appId: '1:671381491956:ios:d44641fc984020132dcea1',
    messagingSenderId: '671381491956',
    projectId: 'futko-battle',
    storageBucket: 'futko-battle.firebasestorage.app',
    iosClientId: '671381491956-l7ul5cgpf07bk3b68gnbm0a8ve16ljet.apps.googleusercontent.com',
    iosBundleId: 'com.example.futko',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3RwnQpSYI3WnnnoDTqe9m62gjJtYWzUs',
    appId: '1:671381491956:ios:d44641fc984020132dcea1',
    messagingSenderId: '671381491956',
    projectId: 'futko-battle',
    storageBucket: 'futko-battle.firebasestorage.app',
    iosClientId: '671381491956-l7ul5cgpf07bk3b68gnbm0a8ve16ljet.apps.googleusercontent.com',
    iosBundleId: 'com.example.futko',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAprAmk1hPhlNbkQhgTSjIeEfmFIlfK18M',
    appId: '1:671381491956:web:7debcbda8418b1042dcea1',
    messagingSenderId: '671381491956',
    projectId: 'futko-battle',
    authDomain: 'futko-battle.firebaseapp.com',
    storageBucket: 'futko-battle.firebasestorage.app',
  );
}
