// FutKO — Update Firestore questions with real image URLs
//
// Usage:
//   dart run scripts/update_image_urls.dart
//
// Reads scripts/image_urls.json (generated by download_images.dart)
// and updates all questions in Firestore that have matching types.
// Also re-seeds questions if the collection is empty.
//
// Prerequisites:
//   1. Run: dart run scripts/download_images.dart --urls-only
//   2. This generates scripts/image_urls.json

import 'dart:convert';
import 'dart:io';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:futko/firebase_options.dart';

const _urlMapFile = 'scripts/image_urls.json';
const _batchSize = 400;

Future<void> main() async {
  // Load URL map
  final urlMapFile = File(_urlMapFile);
  if (!await urlMapFile.exists()) {
    print('ERROR: $_urlMapFile not found.');
    print('Run first: dart run scripts/download_images.dart --urls-only');
    exit(1);
  }

  final urlMap = jsonDecode(await urlMapFile.readAsString()) as Map<String, dynamic>;
  final badges = (urlMap['badges'] as Map?)?.cast<String, String>() ?? <String, String>{};
  final stadiums = (urlMap['stadiums'] as Map?)?.cast<String, String>() ?? <String, String>{};
  final silhouettes = (urlMap['silhouettes'] as Map?)?.cast<String, String>() ?? <String, String>{};
  final competitions = (urlMap['competitions'] as Map?)?.cast<String, String>() ?? <String, String>{};

  print('''
========================================
  FutKO - Update Image URLs in Firestore
  Badges:       ${badges.length} URLs
  Stadiums:     ${stadiums.length} URLs
  Silhouettes:  ${silhouettes.length} URLs
  Competitions: ${competitions.length} URLs
========================================
  ''');

  // Init Firebase
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  final db = FirebaseFirestore.instance;
  print('Connected to Firestore: ${db.app.options.projectId}');

  int updated = 0;
  int skipped = 0;

  // Process all questions
  final snapshot = await db.collection('questions').get();
  print('Found ${snapshot.docs.length} questions in Firestore\n');

  for (int i = 0; i < snapshot.docs.length; i += _batchSize) {
    final batch = db.batch();
    final end = (i + _batchSize).clamp(0, snapshot.docs.length);

    for (int j = i; j < end; j++) {
      final doc = snapshot.docs[j];
      final data = doc.data();
      final type = data['type'] as String? ?? '';
      String? newUrl;

      switch (type) {
        case 'badge':
          newUrl = _lookupUrl(badges, data);
          break;
        case 'stadium':
          newUrl = _lookupUrl(stadiums, data);
          break;
        case 'playerImage':
          newUrl = _lookupUrl(silhouettes, data);
          break;
        case 'competition':
          newUrl = _lookupUrl(competitions, data);
          break;
      }

      if (newUrl != null) {
        batch.update(doc.reference, {'imageUrl': newUrl});
        updated++;
      } else {
        skipped++;
      }
    }

    await batch.commit();
    print('  Batch: ${end.clamp(0, snapshot.docs.length)} / ${snapshot.docs.length} processed');
  }

  print('''
========================================
  Done! Updated: $updated  Skipped: $skipped
========================================
  ''');
}

/// Try to find a matching URL for a question by checking the correctAnswer
/// and options fields against the URL map keys.
String? _lookupUrl(Map<String, String> urlMap, Map<String, dynamic> questionData) {
  // Try correctAnswer first (most reliable for badge/stadium/playerImage)
  final correctAnswer = questionData['correctAnswer'] as String? ?? '';
  final slug = _slugify(correctAnswer);
  if (urlMap.containsKey(slug)) return urlMap[slug];

  // Try exact correctAnswer as key (in case it matches without slugify)
  if (urlMap.containsKey(correctAnswer.toLowerCase())) {
    return urlMap[correctAnswer.toLowerCase()];
  }

  // Try options (the correct answer should be in there)
  final options = questionData['options'] as List? ?? [];
  for (final opt in options) {
    final optSlug = _slugify(opt.toString());
    if (urlMap.containsKey(optSlug)) return urlMap[optSlug];
  }

  return null;
}

String _slugify(String name) {
  return name
      .toLowerCase()
      .replaceAll('á', 'a').replaceAll('é', 'e')
      .replaceAll('í', 'i').replaceAll('ó', 'o')
      .replaceAll('ú', 'u').replaceAll('ñ', 'n')
      .replaceAll('ü', 'u').replaceAll('ä', 'a')
      .replaceAll('ö', 'o')
      .replaceAll(RegExp(r"[^a-z0-9]+"), '_')
      .replaceAll(RegExp(r'^_|_$'), '');
}
